Scraping https://quotes.toscrape.com/

Installing libraries

In [1]:
!python3 -m pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.15.0)
Requirement already satisfied: pandas in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

Storing url and checking response

In [3]:
url = "https://quotes.toscrape.com/" 
url

'https://quotes.toscrape.com/'

In [4]:
response = requests.get(url, timeout=30)
response

Checking website html code

In [5]:
html = response.text

In [6]:
print(html[10000:15000])

m">
            <a class="tag" style="font-size: 10px" href="/tag/friendship/">friendship</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/friends/">friends</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/truth/">truth</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 6px" href="/tag/simile/">simile</a>
            </span>


    </div>
</div>

    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
            </p>
            <p class="copyright">
                Made with <span class='zyte'>❤</span> by <a class='zyte' href="https://www.zyte.com">Zyte</a>
            </p>
        </div>
    </footer>
</body>
</html>

Turning html into beautifulsoup object

In [7]:
soup = BeautifulSoup(html, "html.parser")
type(soup)

bs4.BeautifulSoup

Finding page heading

In [8]:
heading = soup.find("h1")
heading

<h1>
<a href="/" style="text-decoration: none">Quotes to Scrape</a>
</h1>

In [9]:
heading.get_text

<bound method PageElement.get_text of <h1>
<a href="/" style="text-decoration: none">Quotes to Scrape</a>
</h1>>

In [10]:
heading.get_text(strip=True)

'Quotes to Scrape'

Finding first quote and all quotes on page

In [11]:
first_quote = soup.select_one("div.quote")

In [12]:
first_quote

<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
<a class="tag" href="/tag/change/page/1/">change</a>
<a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
<a class="tag" href="/tag/thinking/page/1/">thinking</a>
<a class="tag" href="/tag/world/page/1/">world</a>
</div>
</div>

In [13]:
all_quotes = soup.select("div.quote")

In [14]:
all_quotes

[<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
 <a class="tag" href="/tag/change/page/1/">change</a>
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>
 <a class="tag" href="/tag/world/page/1/">world</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
 <span>by <small class="author" itemprop="author">J.K. Rowling</small>
 <a href="/author/J-K-Rowling">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
 <a class="tag" href="/tag/abilities/page/1/">abilities</a>
 <a class="tag" href="/tag/choices/page/1/">choices</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/live/page/1/">live</a>
 <a class="tag" href="/tag/miracle/page/1/">miracle</a>
 <a class="tag" href="/tag/miracles/page/1/">miracles</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
 <span>by <small class="author" itemprop="author">Jane Austen</small>
 <a href="/author/Jane-Austen">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
 <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
 <a class="tag" href="/tag/books/page/1/">books</a>
 <a class="tag" href="/tag/classic/page/1/">classic</a>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
 <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
 <a href="/author/Marilyn-Monroe">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
 <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
 <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
 <a class="tag" href="/tag/success/page/1/">success</a>
 <a class="tag" href="/tag/value/page/1/">value</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
 <span>by <small class="author" itemprop="author">André Gide</small>
 <a href="/author/Andre-Gide">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="life,love" itemprop="keywords"/>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/love/page/1/">love</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
 <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
 <a href="/author/Thomas-A-Edison">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
 <a class="tag" href="/tag/edison/page/1/">edison</a>
 <a class="tag" href="/tag/failure/page/1/">failure</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
 <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
 <a href="/author/Eleanor-Roosevelt">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
 <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
 <span>by <small class="author" itemprop="author">Steve Martin</small>
 <a href="/author/Steve-Martin">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 <a class="tag" href="/tag/obvious/page/1/">obvious</a>
 <a class="tag" href="/tag/simile/page/1/">simile</a>
 </div>
 </div>]

Finding quote text and name of the author

In [15]:
quote_text = first_quote.select_one("span")

In [16]:
quote_text

In [17]:
quote_name = first_quote.select_one("small")

In [18]:
quote_name

Finding tags on quote

In [19]:
quote_tags = first_quote.select("a")

In [20]:
quote_tags

[<a href="/author/Albert-Einstein">(about)</a>,
 <a class="tag" href="/tag/change/page/1/">change</a>,
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>,
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>,
 <a class="tag" href="/tag/world/page/1/">world</a>]

Storing author url

In [ ]:
author_relative_url = quote.select_one("span a")["href"]
    author_full_url = urljoin(url, author_relative_url)

Storing one quote as dictionary

In [21]:
first_quote_data = {
    "quote_text": quote_text,
    "quote_name": quote_name,
    "quote_tags": quote_tags,
}

In [22]:
first_quote_data

{'quote_text': <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>,
 'quote_name': <small class="author" itemprop="author">Albert Einstein</small>,
 'quote_tags': [<a href="/author/Albert-Einstein">(about)</a>,
  <a class="tag" href="/tag/change/page/1/">change</a>,
  <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>,
  <a class="tag" href="/tag/thinking/page/1/">thinking</a>,
  <a class="tag" href="/tag/world/page/1/">world</a>]}

Findind all quotes data

In [23]:
quotes = soup.select("div.quote")
len(quotes)

10

for looping through the quotes

In [31]:
for quote in quotes:
    name = quote.select_one("span small").text
    print(name)

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin

Creating rows, then dataframe

In [34]:
rows = []
#for looping quotes to store text, name and tags
for quote in quotes:
    text = quote.select_one("span.text").get_text(strip=True)
    author = quote.select_one("small.author").get_text(strip=True)
    quote_tags = quote.select("a")
    rows.append({
        "quote_text": text,
        "author": author,
        "quote_tags": quote_tags
    })
len(rows)

10

In [36]:
df = pd.DataFrame(rows)
df.head()

,quote_text,author,quote_tags
0,“The world as we have created it is a process ...,Albert Einstein,"[[(about)], [change], [deep-thoughts], [thinki..."
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[[(about)], [abilities], [choices]]"
2,“There are only two ways to live your life. On...,Albert Einstein,"[[(about)], [inspirational], [life], [live], [..."
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[[(about)], [aliteracy], [books], [classic], [..."
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[[(about)], [be-yourself], [inspirational]]"

In [37]:
df.shape

(10, 3)

In [38]:
df.columns

Index(['quote_text', 'author', 'quote_tags'], dtype='str')

In [39]:
df.info

<bound method DataFrame.info of                                           quote_text             author  \
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin

                                          quote_tags
0  [[(about)], [change], [deep-thoughts], [thinki...
1                [[(about)], [abilities], [choices]]
2  [[(about)], [inspirational], [life], [live], [...
3  [[(about)], [aliteracy], [books], [classic], [...
4        [[(about)], [be-yourself], [inspirational]]
5       [[(about)], [adulthood], [success], [value]]
6                        [[(about)], [life], [love]]
7  [[(about)], [edison], [failure], [inspirationa...
8     [[(about)], [misattributed-eleanor-roosevelt]]
9          [[(about)], [humor], [obvious], [simile]]  >

Finding all Albert Einstein quotes on page

In [40]:
df[df["author"] == "Albert Einstein"]

,quote_text,author,quote_tags
0,“The world as we have created it is a process ...,Albert Einstein,"[[(about)], [change], [deep-thoughts], [thinki..."
2,“There are only two ways to live your life. On...,Albert Einstein,"[[(about)], [inspirational], [life], [live], [..."
5,“Try not to become a man of success. Rather be...,Albert Einstein,"[[(about)], [adulthood], [success], [value]]"